### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by clarkdever** [Sitata/titanium-google-analytics#12]
I'm trying to install this module on windows 7.
I've copied the zip file to the root directory of the project in Titanium Studio (following the process outlined on https://wiki.appcelerator.org/display/guides2/Using+Titanium+Modules#UsingTitaniumModules-GlobalInstallation) but it didn't work to install the module.

Could you please outline the steps to install the module in the README.MD?

**Comment by astjohn** [comment]
OK. Some of this is starting to make sense, but I'm still not confident on what you installed via the GUI.

First, I think you probably downloaded the full source of the module by downloading the github zip file. What you need to do is download each release zip file. 

For iOS, the zips are located at the root of the iOS folder:
https://github.com/Sitata/titanium-google-analytics/tree/master/mobile/ios

For android, the zips are located in the dist folder:
https://github.com/Sitata/titanium-google-analytics/tree/master/mobile/android/dist

Regarding the unlicensed message, this module used to belong to another author who registered the module on the appcelerator marketplace. To use apps on that marketplace, you have to "buy" them (even the free ones) so that they are registered to your developer account. This is how they track paid modules. 

I had hoped that changing the module's identifier would fix this problem for new users such as yourself. To confirm, please make sure you are using version 2.2.0 for android and version 2.1.0 for iOS. Those are the latest versions which have an updated module identifier. You can specify the exact version to use in your `<module>` definition to be sure or simply uninstall everything and make sure only those versions remain.

Let me know how it goes.

**Comment by clarkdever** [comment]
Hi Adam,
Thanks for helping me work through this.  I've got it working today!

I appreciate you supporting this project, it was very helpful to me.

Clark Dever
Rogue Technologist
716.803.3213
clark@clarkdever.com
http://www.clarkdever.com
http://about.me/clarkdever

Please excuse my brevity: http://five.sentenc.es/

**Comment by astjohn** [comment]
No problem. Glad to hear it!

I just want to make sure about that licensing issue thing. Did the newest version of this module eliminate it? Or did you end up registering on the appcelerator marketplace?

**Comment by clarkdever** [comment]
I was previously registered with the 1.0 version.

When I installed your latest version (with the commit comment about
licensing), I had no further issues with licensing.

Clark Dever
Rogue Technologist
716.803.3213
clark@clarkdever.com
http://www.clarkdever.com
http://about.me/clarkdever

Please excuse my brevity: http://five.sentenc.es/
