### ISSUE TITLE
Module not found on Android

### ISSUE THREAD

**Issue by astjohn** [Sitata/titanium-google-analytics#17]
Need to fix naming of jar file during build as per:
https://github.com/Sitata/titanium-google-analytics/issues/13#issuecomment-70508249

This will fix the module missing error that some have experienced on Android.

**Comment by EnCz** [comment]
Just to get things straight, this is not an Android problem.
Like I mentioned in https://github.com/Sitata/titanium-google-analytics/issues/13#issuecomment-70509585 the real issue is, that Linux's filesystems are (usually) case-sensitive. 
Titanium build expects a googleanalytics.jar, the actual jar however is called googleAnalytics.jar.

This caused a lot of confusion because my coworker (who uses OSX) could build and run the project without any problems. 
This is due HFS+ (the Mac filesystem) is usually configured to be case insensitive.

**Comment by astjohn** [comment]
Hopefully fixed by 7271678b16f6183de385b64dc627161dc2201b24 and Version 3.1.0.
